version: '3'
services:
  php:
    container_name: php
    image: pprofile:latest
    networks:
      - pprofile
    environment:
      TZ: 'Asia/Shanghai'
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - 8086:8086
      - 8088:8088/udp
    networks:
      - pprofile
    environment:
      TZ: 'Asia/Shanghai'
      INFLUXDB_ADMIN_ENABLED: 'true'
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - pprofile
    ports:
      - 3000:3000
    environment:
      TZ: 'Asia/Shanghai'
networks:
  pprofile:
